### ISSUE TITLE
Add retry to ESI calls

### ISSUE THREAD

**Issue by lockefox** [EVEprosper/ProsperAPI#13]
ESI calls are failing ~1%.  Add [retry](https://pypi.python.org/pypi/retry/)

```python
[ERROR:crest_utils.py--fetch_market_history:354]
ERROR: unable to fetch market history from CREST
    type_id: 39
    region_id: 10000002
Traceback (most recent call last):
  File "/opt/venvs/prosper-api/lib/python3.5/site-packages/publicAPI/crest_utils.py", line 343, in fetch_market_history
    config=config
  File "/opt/venvs/prosper-api/lib/python3.5/site-packages/publicAPI/crest_utils.py", line 303, in fetch_esi_endpoint
    req.raise_for_status()
  File "/opt/venvs/prosper-api/lib/python3.5/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://esi.tech.ccp.is/latest/markets/10000002/history/?datasource=tranquility&type_id=39
[ERROR:forecast_utils.py--fetch_extended_history:201]
ERROR: trouble getting data from CREST
    region_id=10000002
    type_id=39
Traceback (most recent call last):
  File "/opt/venvs/prosper-api/lib/python3.5/site-packages/publicAPI/crest_utils.py", line 343, in fetch_market_history
    config=config
  File "/opt/venvs/prosper-api/lib/python3.5/site-packages/publicAPI/crest_utils.py", line 303, in fetch_esi_endpoint
    req.raise_for_status()
  File "/opt/venvs/prosper-api/lib/python3.5/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://esi.tech.ccp.is/latest/markets/10000002/history/?datasource=tranquility&type_id=39

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/prosper-api/lib/python3.5/site-packages/publicAPI/forecast_utils.py", line 194, in fetch_extended_history
    logger=logger
  File "/opt/venvs/prosper-api/lib/python3.5/site-packages/publicAPI/crest_utils.py", line 361, in fetch_market_history
    mode.name
publicAPI.exceptions.CRESTBadMarketData```

**Comment by lockefox** [comment]
Fixed by @xiantra-eve, released in v1.2.1
